spring:
  application:
    name: gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
zuul:
  routes:
    user-management-service:
        path: /user/**
        uri: 192.158.1.5:8001

  sleuth:
    sampler:
      percentage:1.0
    web:
      additional-skip-pattern: (^cleanup.*|.+favicon.*)
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    region: default
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://192.168.1.5:8761/eureka