spring:
  application:
    name: gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
    loadbalancer:
      ribbon:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://192.168.1.32:8083/auth/realms/smartfactory
          jwkSetUri: http://192.168.1.32:8083/auth/realms/smartfactory/protocol/openid-connect/certs
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    region: default
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://discUser:discPassword@192.168.1.32:8761/eureka
ribbon:
  eureka:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

