version: "3.7"
services:
  mongodb:
    image: "mongo:4.2"
    hostname: mongo-db
    container_name: mongo-db
    restart: always
    privileged: true
    volumes:
     - mongo_storage:/data/db
    expose: 
     - 27017
    ports:
     - 27017:27017

  mqtt:
    image: "eclipse-mosquitto:latest"
    hostname: mosquitto
    container_name: mosquitto
    restart: always
    privileged: true
    expose: 
     - 1883
    ports:
     - 1883:1883

volumes: 
  mongo_storage:
