spring:
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://keycloak:8083/auth/realms/smartfactory
          jwkSetUri: http://keycloak:8083/auth/realms/smartfactory/protocol/openid-connect/certs
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      uri: 192.168.1.4:8888
  data:
    mongodb:
      database: smartfactory-notification
      host: 192.168.1.4
      port: 27017
  rabbitmq:
    host: 192.168.1.4
    port: 5672
    username: admin
    password: admin
server:
  port: 8004
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@192.168.1.4:8761/eureka
mqtt:
  publisher-id: spring-server
  server: tcp://192.168.1.4:1883
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


